# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'mongoid_ext'
  s.version = '0.8.0'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.authors = ['David A. Cuadrado']
  s.date = '2012-07-27'
  s.description = 'mongoid plugins'
  s.email = 'krawek@gmail.com'
  s.executables = ['mongoid_console']
  s.extra_rdoc_files = %w(LICENSE README.rdoc)
  s.files =  %w(LICENSE VERSION README.rdoc Rakefile) + Dir.glob('{lib,test}/**/*')
  s.homepage = 'http://github.com/dcu/mongoid_ext'
  s.require_paths = ['lib']
  s.rubygems_version = '1.8.24'
  s.summary = 'mongoid plugins'

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mongoid>, ['~> 4'])
      s.add_runtime_dependency(%q<uuidtools>, ['>= 2.1.1'])
      s.add_runtime_dependency(%q<i18n>, ['>= 0'])
      s.add_runtime_dependency(%q<tzinfo>, ['>= 0'])
      s.add_runtime_dependency(%q<differ>, ['>= 0.1.2'])
      s.add_runtime_dependency(%q<encryptor>, ['~> 1.1.3'])
      s.add_runtime_dependency(%q<rack>, ['>= 0'])
      s.add_runtime_dependency(%q<mongoid-grid_fs>, ['>= 0'])
      s.add_development_dependency(%q<yard>, ['~> 0.6.0'])
      s.add_development_dependency(%q<jeweler>, ['~> 1.8.4'])
      s.add_development_dependency(%q<shoulda>, ['~> 2.11.3'])
      s.add_development_dependency(%q<jnunemaker-matchy>, ['~> 0.4'])
      s.add_development_dependency(%q<shoulda>, ['~> 2.11.3'])
      s.add_development_dependency(%q<mocha>, ['~> 0.11.4'])
      s.add_development_dependency(%q<timecop>, ['>= 0'])
      s.add_development_dependency(%q<pry>, ['>= 0'])
    else
      s.add_dependency(%q<mongoid>, ['~> 4'])
      s.add_dependency(%q<uuidtools>, ['>= 2.1.1'])
      s.add_dependency(%q<i18n>, ['>= 0'])
      s.add_dependency(%q<tzinfo>, ['>= 0'])
      s.add_dependency(%q<differ>, ['>= 0.1.2'])
      s.add_dependency(%q<encryptor>, ['~> 1.1.3'])
      s.add_dependency(%q<rack>, ['>= 0'])
      s.add_dependency(%q<mongoid-grid_fs>, ['>= 0'])
      s.add_dependency(%q<yard>, ['~> 0.6.0'])
      s.add_dependency(%q<jeweler>, ['~> 1.8.4'])
      s.add_dependency(%q<shoulda>, ['~> 2.11.3'])
      s.add_dependency(%q<jnunemaker-matchy>, ['~> 0.4'])
      s.add_dependency(%q<shoulda>, ['~> 2.11.3'])
      s.add_dependency(%q<mocha>, ['~> 0.11.4'])
      s.add_dependency(%q<timecop>, ['>= 0'])
      s.add_dependency(%q<pry>, ['>= 0'])
    end
  else
    s.add_dependency(%q<mongoid>, ['~> 4'])
    s.add_dependency(%q<uuidtools>, ['>= 2.1.1'])
    s.add_dependency(%q<i18n>, ['>= 0'])
    s.add_dependency(%q<tzinfo>, ['>= 0'])
    s.add_dependency(%q<differ>, ['>= 0.1.2'])
    s.add_dependency(%q<encryptor>, ['~> 1.1.3'])
    s.add_dependency(%q<rack>, ['>= 0'])
    s.add_dependency(%q<mongoid-grid_fs>, ['>= 0'])
    s.add_dependency(%q<yard>, ['~> 0.6.0'])
    s.add_dependency(%q<jeweler>, ['~> 1.8.4'])
    s.add_dependency(%q<shoulda>, ['~> 2.11.3'])
    s.add_dependency(%q<jnunemaker-matchy>, ['~> 0.4'])
    s.add_dependency(%q<shoulda>, ['~> 2.11.3'])
    s.add_dependency(%q<mocha>, ['~> 0.11.4'])
    s.add_dependency(%q<timecop>, ['>= 0'])
    s.add_dependency(%q<pry>, ['>= 0'])
  end
end

